"use client"
import '@/app/globals.css'
import { Inter } from 'next/font/google'
import { CacheProvider } from '@emotion/react'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns'
import createCache from '@emotion/cache'
import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material/styles'
import { createTheme } from '@mui/material/styles'
import { Metadata } from 'next';
// import { Providers } from '@/store/provider';
// import { store } from '@/store';

const theme = createTheme({})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cache = createCache({
  key: 'css',
  prepend: true,
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			{/* <Providers> */}
				<CacheProvider value={cache}>
					<LocalizationProvider dateAdapter={AdapterDateFns}>
						<body>
							<ThemeProvider theme={theme}>
								<CssBaseline />
								{children}
							</ThemeProvider>
						</body>
					</LocalizationProvider>
				</CacheProvider>
			{/* </Providers> */}
		</html>
  )
}
